---
 - name: install required packages
   apt: update_cache=yes cache_valid_time=600
   apt: pkg={{item}} state=installed
   with_items:
     - vim
     - curl
     - wget
     - docker.io
     - git
     - wget
     - vim
     - nano
     - zip
     - unzip
     - ntp



